language: rust
# Use bionic or later to use fcitx-4.2.9.2 or later.
dist: bionic
cache: cargo
rust:
  - stable
  - beta
  - 1.39.0
jobs:
  include:
    - rust: 1.39.0
      env: TEST_MINIMAL_VERSIONS=1
    - rust: 1.39.0
      env: LINT=1
before_install:
  - sudo apt-get -y install fcitx-libs-dev
  - |
    if [ "${LINT:-0}" -ne 0 ] ; then
        rustup component add clippy rustfmt
        cargo clippy --version
        cargo fmt --version
    fi
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        rustup install nightly
    fi
before_script:
  # Use dependencies with minimal versions.
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        cargo +nightly update -Z minimal-versions
    fi
script:
  - cargo build --verbose --workspace --all-features && cargo test --verbose --workspace --all-features
  # Fail if the code is correctly formatted.
  - if [ "${LINT:-0}" -ne 0 ] ; then cargo fmt --all -- --check ; fi
  # Fail if the code has warnings.
  - if [ "${LINT:-0}" -ne 0 ] ; then cargo clippy --all-features -- --deny warnings ; fi
notifications:
  email: false
